# Site
repository: Illest70/modern-resume-theme

# Content configuration version
version: 2

# Personal info
name: Ely Terrazas
title: Data Analyst/Data Scientist
email: elyterrazas74@gmail.com
phone: (303)-808-5257

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: Illest70
linkedin_username: ely-terrazas-43806026b

# About Section
about_content: |
  I am a passionate and detail-oriented individual with a deep love for computer science and the art of organizing and developing data. I thrive on transforming raw information into meaningful insights.

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: Bike Rental data
        link: https://github.com/Illest70/Sales-Data-Analysis-with-Python
        link_text: View on GitHub

      - layout: left
        title: SQL Database Optimization
        link: https://github.com/Illest70/biodiversity-national-parks-project
        link_text: View on GitHub

      - layout: left
        title: Data Visualization with Tableau
        link: https://public.tableau.com/app/profile/your-username
        link_text: View on Tableau

      - layout: left
        title: Parallax Scrolling Website
        link: https://codepen.io/Ely-terrazas/pen/Pordogj
        link_text: View on CodePen

      - layout: left
        title: Interactive Calculator
        link: https://codepen.io/Ely-terrazas/pen/JjQwXwW
        link_text: View on CodePen

      - layout: left
        title: Weather Dashboard
        link: https://codepen.io/Ely-terrazas/pen/yLdZOEw
        link_text: View on CodePen

      - layout: left
        title: CSS Art: Geometric Shapes
        link: https://codepen.io/Ely-terrazas/pen/GRbzZaQ
        link_text: View on CodePen

      - layout: left
        title: Animated Landing Page
        link: https://codepen.io/Ely-terrazas/pen/YzoBWRJ
        link_text: View on CodePen

  - title: Certifications
    layout: list
    content:
      - layout: right
        title: Responsive Web Design Certification
        sub_title: freeCodeCamp
        caption: Issued 2024
        description: |
          Skills Gained: HTML, CSS, JavaScript, responsive design principles.

      - layout: right
        title: JavaScript Algorithms and Data Structures Certification
        sub_title: freeCodeCamp
        caption: Issued 2024
        description: |
          Skills Gained: Advanced JavaScript, problem-solving, algorithm optimization.

      - layout: right
        title: Front-End Development Libraries Certification
        sub_title: freeCodeCamp
        caption: Issued 2024
        description: |
          Skills Gained: React, Bootstrap, front-end development best practices.

      - layout: right
        title: Data Engineering Certification
        sub_title: Codecademy
        caption: Issued 2025
        description: |
          Skills Gained: Data pipelines, ETL processes, database management, big data tools.

  - title: Skills
    layout: text
    content: |
      ### Programming Languages
      - Python
      - SQL
      - HTML
      - CSS
      - Java

      ### Data Analysis Tools
      - Pandas
      - NumPy
      - Matplotlib
      - Seaborn
      - Tableau

      ### Databases
      - MySQL
      - PostgreSQL

      ### Other Skills
      - Data Cleaning
      - Exploratory Data Analysis (EDA)
      - Data Visualization
      - Statistical Analysis
      - Machine Learning Basics

  - title: A Little More About Me
    layout: text
    content: |
      I am passionate about leveraging data to solve complex problems and drive decision-making. In my free time, I enjoy exploring new datasets, learning about emerging technologies, and contributing to open-source projects. I am always eager to take on new challenges and collaborate with like-minded individuals.

# Footer
footer_show_references: true

# Plugins
plugins:
  - jekyll-seo-tag

# Exclude unnecessary files for deployment
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "lib/"
  - "scripts/"
  - "docker-compose.yml"
