# Site
repository: your-username/modern-resume-theme  # Replace with your GitHub repository name
# favicon: images/favicon.ico  # Optional, add if you have a favicon

# Content configuration version
version: 2

# Personal info
name: Ely Terrazas
title: Aspiring Data Analyst/Data Scientist
email: elyterrazas74@gmail.com
phone: (303)-808-5257

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username:  # Leave blank or add your Twitter handle
github_username: Illest70  # Replace with your GitHub username
stackoverflow_username:  # Leave blank or add your Stack Overflow ID
linkedin_username: Ely Terrazas  # Replace with your LinkedIn username

# Additional icon links
additional_links:
  - title: Portfolio
    icon: fas fa-globe
    url: https://illest70.github.io  # Replace with your portfolio URL

# About Section
about_profile_image: images/profile.jpg  # Replace with the path to your profile image
about_content: |
  I am a passionate and detail-oriented individual with a deep love for computer science and the art of organizing and developing data. I believe that data is only as powerful as the mind that interprets it, and I thrive on transforming raw information into meaningful insights. With a strong foundation in Python, SQL, and data visualization tools, I am eager to apply my technical skills and analytical mindset to solve real-world problems. My goal is to contribute to data-driven decision-making and continue growing as a data professional.

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: Bike Rental data
        link: https://github.com/Illest70/Sales-Data-Analysis-with-Python  # Replace with your project link
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/your-username/sales-data-analysis  # Replace with your project link
        description: |
          Analyzed a dataset of sales transactions to identify trends, top-performing products, and customer behavior. Used Python libraries like Pandas and Matplotlib for data cleaning, analysis, and visualization.

      - layout: left
        title: SQL Database Optimization
        link: https://github.com/Illest70/biodiversity-national-parks-project  # Replace with your project link
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/your-username/sql-database-optimization  # Replace with your project link
        description: |
          Designed and queried a relational database to optimize data retrieval and improve query performance. Wrote complex SQL queries to extract insights from large datasets.

      - layout: left
        title: Data Visualization with Tableau
        link: https://public.tableau.com/app/profile/your-username  # Replace with your Tableau profile link
        link_text: View on Tableau
        additional_links:
          - title: Tableau Profile
            icon: fas fa-chart-bar
            url: https://public.tableau.com/app/profile/your-username  # Replace with your Tableau profile link
        description: |
          Created interactive dashboards in Tableau to visualize key metrics from a dataset, such as sales performance, customer demographics, and regional trends.

      - layout: left
        title: Predictive Modeling with Python
        link: https://github.com/your-username/predictive-modeling  # Replace with your project link
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/your-username/predictive-modeling  # Replace with your project link
        description: |
          Built a simple machine learning model (e.g., linear regression or decision tree) to predict outcomes based on historical data. Used Scikit-learn for model training and evaluation.

      - layout: left
        title: Web Scraping and Data Collection
        link: https://github.com/your-username/web-scraping  # Replace with your project link
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/your-username/web-scraping  # Replace with your project link
        description: |
          Developed a Python script to scrape data from a website and store it in a structured format for analysis. Used libraries like BeautifulSoup and Requests.

  - title: Certifications
    layout: list
    content:
      - layout: right
        title: Responsive Web Design Certification
        sub_title: freeCodeCamp
        caption: Issued 2024
        description: |
          Skills Gained: HTML, CSS, JavaScript, responsive design principles.

      - layout: right
        title: JavaScript Algorithms and Data Structures Certification
        sub_title: freeCodeCamp
        caption: Issued 2024
        description: |
          Skills Gained: Advanced JavaScript, problem-solving, algorithm optimization.

      - layout: right
        title: Front-End Development Libraries Certification
        sub_title: freeCodeCamp
        caption: Issued 2024
        description: |
          Skills Gained: React, Bootstrap, front-end development best practices.

      - layout: right
        title: Data Engineering Certification
        sub_title: Codecademy
        caption: Issued 2025
        description: |
          Skills Gained: Data pipelines, ETL processes, database management, big data tools.

  - title: Skills
    layout: text
    content: |
      ### Programming Languages
      - Python
      - SQL
      - HTML
      - CSS
      - Java

      ### Data Analysis Tools
      - Pandas
      - NumPy
      - Matplotlib
      - Seaborn
      - Tableau

      ### Databases
      - MySQL
      - PostgreSQL

      ### Other Skills
      - Data Cleaning
      - Exploratory Data Analysis (EDA)
      - Data Visualization
      - Statistical Analysis
      - Machine Learning Basics

  - title: A Little More About Me
    layout: text
    content: |
      I am passionate about leveraging data to solve complex problems and drive decision-making. In my free time, I enjoy exploring new datasets, learning about emerging technologies, and contributing to open-source projects. I am always eager to take on new challenges and collaborate with like-minded individuals.

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "lib/"
  - "scripts/"
  - "docker-compose.yml"
